added github action
knox-networks/grpcui pull request #1
Opened 2022-12-19 15:28 UTC by echenknox

2022-12-20 02:15 UTC, echenknox commented on .github/release.yml
> +    types: [closed]
yeah, make sense. 
Added.

2022-12-20 15:57 UTC, kbeckman requested changes
There were a lot of changes other than what' is described in your PR title... Please consider providing PR reviewers with a thorough description of the work done so they can spend less time figuring out what was actually changed in a PR.

2022-12-20 15:57 UTC, kbeckman commented on .github/build.yml
> +    types: [opened, reopened]
Please remove the `types` key so the build workflow runs when any change is added to a PR... This configuration is insufficient and will only execute when a PR is opened. If there's any work that needs to be done after the initial PR creation, none of it is tested in the build pipeline which you can verify by checking the "Actions" tab for this project. There still haven't been any workflows that have executed for this repo...

2022-12-20 15:57 UTC, kbeckman commented on .github/build.yml
> +    runs-on: self-hosted
Please ensure this workflow runs on `ubuntu-latest`. Part of our overall migration process is to move to native GHA runners where we're able to and refactor the pipelines accordingly. Since we're only building a container image here, we should be able to run this on a native GHA runner simply by changing this (unless there's some dependency I'm not aware of).

If we decide we absolutely need `self-hosted` runners for some of Knox's projects, then we can build those... But that'll have to be done via a repeatable process and some sort of IaC deployment when we move them to the LZ.

2022-12-20 15:57 UTC, kbeckman commented on .github/build.yml
> +          make ci
`make ci` doesn't actually build the container image... Since the purpose of these pipelines is to generate a container image for a Knox sidecar service, I think we should actually build the image as part of the CI process. Here `make docker` would meet the requirement.

2022-12-20 15:57 UTC, kbeckman commented on .github/release.yml
> +    runs-on: self-hosted
_Same response to `self-hosted`..._

2022-12-21 03:01 UTC, echenknox commented on .github/build.yml
> +    runs-on: self-hosted
I changed to ubuntu-latest. It is a simple change.

2022-12-21 03:21 UTC, echenknox commented on .github/build.yml
> +          make ci
@kbeckman, `make ci` makes a lot of sense in the build job. It is created for this purpose. It does the following tasks:
```
ci: deps checkgofmt vet staticcheck ineffassign predeclared test
```
It confirms the code is working as expected. The dependencies are up to date etc.
`make docker` create docker image is only needed if I want to release the build as an image.

2022-12-21 03:21 UTC, echenknox commented on .github/release.yml
> +    runs-on: self-hosted
done.

2022-12-21 03:23 UTC, echenknox commented on .github/build.yml
> +          make ci
The extra changes I made are problems found after I ran `make ci`. Those are all deprecated libraries. Changes are to replace those deprecated libraries.

2022-12-21 15:30 UTC, kbeckman commented on .github/build.yml
> +          make ci
> @kbeckman, `make ci` makes a lot of sense in the build job. It is created for this purpose. It does the following tasks:
> 
> ```
> ci: deps checkgofmt vet staticcheck ineffassign predeclared test
> ```
> 
> It confirms the code is working as expected. The dependencies are up to date etc. `make docker` create docker image is only needed if I want to release the build as an image.

I wasn't asking to remove `make ci` and replace it with `make docker`... I was suggesting we add that in addition to `make ci` so you could actually verify the docker container you're building in the release pipeline actually builds. If you think that's an unreasonable request, please request another reviewer.

Following is an example of the `sandbox` application building a container as part of a non-release CI workflow via the shared Knox `github-actions/build-container" task. With that shared task the "push" option is false for non-release workflows - you must opt-in (which we do in the release workflow).
  * https://github.com/knox-networks/sandbox/blob/main/.github/workflows/build.yml#L41

2022-12-21 15:39 UTC, kbeckman commented on .github/release.yml
> +    types: [closed]
Please refer to the example I added in my prior comment where I suggested to modify the `build.yml` file with `on: pull_reuqest`... Your branch filter will only run if if the source branch is named `knox-develop`. Since that's your target branch in this case, the build step that you've added for this PR still hasn't and won't run. I can confirm with certainty that you haven't tested any of this because there is no history of any GHA pipelines being run at the time of this comment. Please verify here: https://github.com/knox-networks/grpcui/actions

2022-12-21 15:41 UTC, kbeckman commented on .github/release.yml
> +    types: [closed]
![image](https://user-images.githubusercontent.com/782327/208944284-5a7d384c-b65c-4a31-a741-c8e88c29f2f8.png)
No CI Runs?

2022-12-22 03:39 UTC, echenknox commented on .github/release.yml
> +    types: [closed]
@kbeckman , the "branches" is the target branch for the PR. This is intended. I only expect the PR that is created against "knox-develop". This is a forked repo, and I left the "main" branch to sync with the origin. I do not want one to create PR against "main". I can't stop others from making mistakes, but I can control GitHub action not to build it.

The github action only runs if it exists in the "base" branch. In this repo, the base branch is "knox-develop". It is not merged into the "base" branch. That's why it has never run. 

After this PR, the future PR will run whenever a PR is created.

2023-01-06 14:52 UTC, kbeckman commented on .github/release.yml
> +    types: [closed]
@echenknox (cc @fkim7), I wasn't aware this was a public fork and I wasn't aware of the nuances for running GHA workflows from public forks. There wasn't anything in this PR description about the nuances of this particular project or the work that was done here -- you shouldn't leave that up to the reviewer because it takes a significant amount of time to build context for someone who isn't familiar with the code.

However, after some research and additional PR inspection I noticed the reason your builds weren't working is because they aren't in the proper location. Your new workflows are in the `.github` root rather than `.github/workflows` directory that would enable them to be picked up automatically by GHA. _These workflows do indeed work in a forked repo that isn't the fork's base branch._ 

Please refer to my latest commit as confirmation. [This link](https://github.com/knox-networks/grpcui/actions/runs/3856090376) is the GHA workflow invocation for my commit moving the `build.yml` workflow into `.github/workflows`.

2023-01-06 18:35 UTC, echenknox commented on .github/build.yml
> +          make ci
Added hadolint to lint dockerfile.

2023-01-06 18:36 UTC, echenknox commented on .github/release.yml
> +    types: [closed]
Thanks for figuring out the root cause. Yes, it works now.

2023-01-06 19:08 UTC, fkim7 approved these changes

2023-01-06 19:37 UTC, merged